easy:
  min: 20000
  max: 50000
  names:
    - "XM Collected"
    - "XM Recharged"
    - "Lifetime AP"
resonators:
  min: 30
  max: 110
  names:
    - "Glyph Hack Points"
hacking:
  min: 20
  max: 50
  names:
    - "Hacks"
few:
  min: 1
  max: 3
  names:
    - "Drone Hacks"
    - "Distance Walked"
